services:
  medi-eco-book-stack-query-actions:
    image: fluxms/medi-eco-book-stack-query-actions:v2022-03-24-4
    environment:
      - BOOK_STACK_PORT=443
      - BOOK_STACK_HOST=example.com
      - BOOK_STACK_TOKEN=a-token-id:a-token-password
    ports:
      - 127.1.2.8:8500:8500
